[tool.isort]
line_length = 88
known_first_party = ['cachecontrol']
# Set multi-line output to "Vertical Hanging indent" to avoid fighting with black.
multi_line_output = 3
include_trailing_comma = true
